name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  path: ^1.9.0
  sqlite3: ^2.4.2
  shelf: ^1.2.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  shelf_router: ^1.1.4
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
